services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: emailtool-backend
    ports:
      - "8000:8000"
    volumes:
      - ./email_tool/backend/static:/app/email_tool/backend/static
      - screenshots:/app/email_tool/backend/static/screenshots
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql+asyncpg://emailuser:emailpass@postgres:5432/emaildb
    depends_on:
      - postgres

  frontend:
    build:
      context: ./email_tool/frontend
      dockerfile: Dockerfile.frontend
    container_name: emailtool-frontend
    volumes:
      - build:/usr/share/nginx/html
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: emailtool-nginx
    ports:
      - "3000:80"
    volumes:
      - build:/usr/share/nginx/html:ro
      - screenshots:/screenshots:ro
      - ./email_tool/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-emailuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-emailpass}
      - POSTGRES_DB=${POSTGRES_DB:-emaildb}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  screenshots:
  build:
  pgdata: 